import Layout from "./components/Layout";
import "./globals.css";
import { Inter } from "next/font/google";
import AuthProvider from "./utils/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AuthProvider>
      <html lang="en">
        <head>
          <title>Console.love()</title>
          <meta name="description" content={metadata.description} />
          <script async src="https://js.stripe.com/v3/buy-button.js"></script>
        </head>
        <body>
          <Layout></Layout>
          {children}
        </body>
      </html>
    </AuthProvider>
  );
}
